# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_rating_config_path "./fastlane/metadata/ratings_config.json"


app_identifier "com.marlhex.AllFastlane"
username "1992ignacio@gmail.com"
